### ISSUE TITLE
iphoneX崩溃

### ISSUE THREAD

**Issue by tengshuq** [ming1016/GCDFetchFeed#12]
UIApplication *app = [UIApplication sharedApplication];
[app valueForKeyPath:@"statusBar"]valueForKeyPath:@"foregroundView"]
这个方法有BUG，更新一下吧=。=

**Comment by CodeXey** [comment]
[[[app valueForKeyPath:@"statusBar"] valueForKey:@"statusBar"] valueForKeyPath:@"foregroundView"]
