### ISSUE TITLE
请问编译报错怎么解决

### ISSUE THREAD

**Issue by wangchong321** [ming1016/GCDFetchFeed#28]
![image](https://user-images.githubusercontent.com/12257208/166858387-3c55bf93-0fd1-46c7-b8e3-e6022843c1e9.png)

**Comment by JW-chenjingwei** [comment]
你好，来信已收到，谢谢

**Comment by ming1016** [comment]
@wangchong321 已解决，再试试

**Comment by wangchong321** [comment]
已解决
