### ISSUE TITLE
'ReactiveCocoa/RACEXTScope.h' file not found

### ISSUE THREAD

**Issue by CalvinTp** [ming1016/GCDFetchFeed#4]
Hi,
I have cloned GCDFetchFeed locally, ran pod install; and I am also using .xcworkspace to launch Xcode. The code hit with an error with 'ReactiveCocoa/RACEXTScope.h' file not found. 

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Just incase it might help, the error is on SMDB.h which has dependencies on #import <ReactiveCocoa/RACEXTScope.h>

Thanks.

**Comment by CalvinTp** [comment]
I manage to solve this by using using version 2.3 instead. 

pod 'ReactiveCocoa', '~>2.3'

By default it will be version 5.x and above, so change the Podfile version to rev2.3 and it will resolve the error. Hope this will help others.

**Comment by ming1016** [comment]
great！ I fixed
