### ISSUE TITLE
RAC 使用疑问

### ISSUE THREAD

**Issue by cxjwin** [ming1016/GCDFetchFeed#8]
//stack 分页查询
`- (RACSignal *)selectStackWithPage:(NSUInteger)page`

`if (count > 0) {
                [subscriber sendNext:arr];
            } else {
                [subscriber sendError:nil];
            }
            [subscriber sendCompleted];`
是不是应该是:
`if (count > 0) {
                [subscriber sendNext:arr];
                [subscriber sendCompleted];
            } else {
                [subscriber sendError:nil];
            }`

**Comment by ming1016** [comment]
对，多谢
